# Sample example file
#
# project:
#   project_key: 'hms' 
#   hostname: http://10.11.12.13 
#
# google_drive:
#   UPLOAD_FOLDER_ID: '43242kradsad343R9aasda43ttczZm'
#   SERVICE_ACCOUNT_FILE: 'malware-scan-hms-aksdka3asa.json'
#
# email_sender:
#   SENDER_NAME: "HMS Malware Scanning Bot"
#   SENDER_EMAIL: "<username@foo.com"
#   RECIPIENT_EMAIL: "<username@bar.com"
#   APP_PASSWORD: "masj jkla wqeq adsa"
#
# repo_urls:
#   - "https://github.com/RHEnVision/provisioning-frontend"
#   - "https://github.com/RHEnVision/provisioning-backend"

project:
  project_key: '<project_key>' # project key will be used to create html file (eg. project_key.html) inside /var/www/html directory
  hostname: <http://hostname.com> # result will be located at http://hostname.com/project_key.html

google_drive:
  UPLOAD_FOLDER_ID: '<folder-id>' # can be obtained from google-drive url
  SERVICE_ACCOUNT_FILE: '<sa.json>' # can be generated through google-cloud consle

email_sender:
  SENDER_NAME: "Malware Scanning Bot"
  SENDER_EMAIL: "<username@foo.com"
  RECIPIENT_EMAIL: "<username@bar.com"
  APP_PASSWORD: "<app-password>" # can be obtained from https://myaccount.google.com/apppasswords

repo_urls:
  - "https://github.com/foo/bar.git"
  - "https://github.com/bar/foo.git"
